apiVersion: v1
kind: Service
metadata:
  name: service1
  labels:
    name: service1
spec:
  type: LoadBalancer
  externalIPs:
    - 192.168.1.101
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: demo-service-1
