apiVersion: v1
kind: Pod
metadata:
  name: demo-service-1
  labels:
    name: demo-service-1
spec:
  containers:
    - name: demo-service-1-container
      image: tkaluzny/demo-service-1
      ports:
        - containerPort: 80
          name: http-server
